### ISSUE TITLE
Question about Validation

### ISSUE THREAD

**Issue by Treemann** [TuSimple/RangeDet#11]
Hi, I have trained the model with your configs.
There are some problems about the testing:
1. 'minival=True' in the config makes it run 'sample_roidb' in tools/test.py, but the definition of 'sample_roidb' is commented, so error occurs.
2. I set 'minival=False' and run the script to generate the prediction .pkl file. When I use the waymo official tool 'compute_detection_metrics_main' to calculate the metrics, error occurs: "Failed to parse predictions."

Could you elaborate how to get the metrics with the .pkl file?

**Comment by abbyxxn** [comment]
Sorry, we created a small validation set in order to speed up testing on the validation set which is the meaning of the 'minival' flag, but we did not provide the code to create minival set. In the normal case, you should set 'minival=False' and it will be tested on the entire validation set. 
On your second question, the .pkl file should not be passed directly to the 'compute_detection_metrics_main'. You can refer to the explanation in the README on how to convert .pkl files to .bin files with the help of the file 'tools/create_prediction_bin_3d.py'.

**Comment by Treemann** [comment]
Got it. Thanks
